### ISSUE TITLE
Underscore labels not working in macro arguments

### ISSUE THREAD

**Issue by svallee-dev** [informedcitizenry/6502.Net#11]
I have a bit of code mutation going on in my project, which requires me to pass the address of code into a macro. It used to work when I passed underscore-prefixed labels (local scoped labels), but it's not working anymore. 

Example of my code:
<img width="463" alt="Screen Shot 2021-11-26 at 4 02 56 PM" src="https://user-images.githubusercontent.com/64298376/143661837-27cd7578-ff10-44f6-ae98-21908f1e9051.png">

**Error: Symbol "_hackReadAddr_d" is not defined.**

I can easily fix it by removing the underscores and it works again, but making these labels global is of course not ideal.

Thanks!

**Comment by informedcitizenry** [comment]
I think it might something in your macro. I tried it myself with something like this and it worked fine:

```

foo .macro bar
    ldx \bar
    .endmacro


_bazz_bazz_
    lda $dead, y
    .foo _bazz_bazz_
 
```

**Comment by informedcitizenry** [comment]
I believe this is fixed now, can you confirm?
