### ISSUE TITLE
Sixty502DotNetParser symbol not found?

### ISSUE THREAD

**Issue by svallee-dev** [informedcitizenry/6502.Net#12]
Hi! Sorry I didn't respond to your latest questions regarding my issues tickets, I was on a hiatus on my project. I'm looking forward to get back to it, and excited with the new direction of you project, leveraging Antlr.

I grabbed latest, but it appears the entire Sixty502DotNetParser symbol is missing. Is there a missing file from the repo by any chance?

**Comment by informedcitizenry** [comment]
Curious. Can you delete and re-clone the repository locally?

**Comment by svallee-dev** [comment]
Ah I see, it requires specific Antlr build steps to generate the files, I think. My problem is that I integrate the 6502.Net code in my existing project, instead of building straight up your executable project. I'll try and tweak my project to make sure I get all the build steps. 

That said, I have a suggestion if you ever think it's a good idea: have your 6502.Net core project build into a DLL instead. That DLL could be wrapped by a simple console executable, but could also be used in a different context like in my tablet app situation.

Anyway, turns out this ticket is specific to me, I'm closing it!  :-)
