### ISSUE TITLE
Something I really miss: A simple way to assemble from string to byte[]

### ISSUE THREAD

**Issue by SuperJMN** [informedcitizenry/6502.Net#13]
Hi :) Really interesting project!

I've taken a look to the code and I found almost impossible to use your library to assemble code **without calling the .exe**.

My goal is to invoke your code from another C# project, so I can avoid writing files to disk. I'd like to get the assembled result as byte[];

I'd expected something like:

```csharp
var assembler = new Z80Assembler();

var source = @"CALL main
HALT
main:
LD hl, 30h
LD (hl), 1
RET";

byte[] output = assembler.Assemble(source);
```

Maybe I'm missing something, but this would be a really good API in my humble opinion :)

I hope you can help me getting something like this out of the code. 
Thanks in advance!

**Comment by informedcitizenry** [comment]
Hi there, if you are customizing the source for your own purposes, you could change the signature of the Assemble method and have it return a byte[] array. The assembled output can be queried from the CodeOutput's GetCompilation method. Something like this:

```c#
public byte[] Assemble()
{
    byte[] bytes = { };
    // ... do a bunch of things and if successful return compiled bytes
    return _services.Output.GetCompilation().ToArray();
}
```

**Comment by SuperJMN** [comment]
Thanks for the info. The problem is that AssemblyController still deals with commandline arguments that require paths to files in the filesystem.

- Is there a way to skip all the commandline part?
- And most importantly, how to assemble from string directly instead of input files?

Thanks a lot!

**Comment by informedcitizenry** [comment]
Ahh I see. I made this as a command line tool. Most options that set behavior are parsed from the options in the command line. Feel free to customize for your purposes of course. Be aware also that the assembler recognizes certain directives in source that can do the same, for instance:

```
   .cpu "z80"
   .format "zx"
```

See the [directives section](https://github.com/informedcitizenry/6502.Net/wiki/Reference#other-directives) in the wiki for more info
