### ISSUE TITLE
Incorrect assembly for the Z80

### ISSUE THREAD

**Issue by SuperJMN** [informedcitizenry/6502.Net#15]
When assembling this code:

```
LABEL ld hl, 1
djnz LABEL
```

It should have assembled as:

```
21
01
00
10
FB
```

However, it assembled as:

```
21
01
00
10
FC
```
Please, notice that the last line is different (**FB** vs **FC**)
Am I missing something?

Thanks!

**Comment by informedcitizenry** [comment]
Thanks I'll take a look. That's a big one.

**Comment by informedcitizenry** [comment]
This is fixed now.
